uniform float time;
uniform vec2 resolution;
uniform float speed;
uniform float fogAmount;
uniform vec3 fogColor;
uniform vec3 camera;
uniform float gamma;
uniform bool overRelaxation;
uniform vec2 mouse;